CREATE OR REPLACE PROCEDURE EDAD (FECHA DATE)
IS 

    VEDAD NUMBER (3);
BEGIN
    SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, FECHA)/12) INTO VEDAD
    FROM DUAL;
    DBMS_OUTPUT.PUT_LINE ('SU EDAD ES DE '||VEDAD);
END;
/


-- hACER UN PROCEDIMIENTO QUE PIDA EL NOMBRE DEL EMPLEADO Y MUESTRE EL CODIGO DEL EMPLEADO Y UNA FUNCION

CREATE OR REPLACE PROCEDURE CODIGO (NOMBRE EMP.ENAME%TYPE)
IS 

    VCODIGO EMP.EMPNO%TYPE;
BEGIN
    SELECT EMPNO INTO VCODIGO
    FROM EMP
    WHERE ENAME = NOMBRE;
    DBMS_OUTPUT.PUT_LINE ('SU CODIGO ES '||VCODIGO);
END CODIGO;
/

CREATE OR REPLACE FUNCTION CODIGOF (NOMBRE EMP.ENAME%TYPE) RETURN NUMBER
IS 

    VCODIGO EMP.EMPNO%TYPE;
BEGIN
    SELECT EMPNO INTO VCODIGO
    FROM EMP
    WHERE ENAME = NOMBRE;
    RETURN VCODIGO;
END CODIGOF;
/


CREATE TABLE EMPLEADOS AS SELECT * FROM EMP;