CREATE OR REPLACE PROCEDURE EDAD (FECHA DATE)
IS 

    VEDAD NUMBER (3);
BEGIN
    SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, FECHA)/12) INTO VEDAD
    FROM DUAL;
    DBMS_OUTPUT.PUT_LINE ('SU EDAD ES DE '||VEDAD);
END;
/


-- hACER UN PROCEDIMIENTO QUE PIDA EL NOMBRE DEL EMPLEADO Y MUESTRE EL CODIGO DEL EMPLEADO Y UNA FUNCION

CREATE OR REPLACE PROCEDURE CODIGO (NOMBRE VARCHAR2)
IS 

    VCODIGO ;
BEGIN
    SELECT DEPTNO INTO VEDAD
    FROM DUAL;
    DBMS_OUTPUT.PUT_LINE ('SU EDAD ES DE '||VEDAD);
END;
/