REPASO GENERAL SQL 1 - ENUNCIADOS
/*
1.- Seleccionar el nombre, apellidos y el tipo de los alumnos cuya
descripción se pida por teclado. Evitar que el usuario escriba minúsculas
por teclado.
*/
/*
2.- Mostrar la media de matrículas con dos decimales, la máxima, mínima,
cuenta y total de matrículas, todas ellas con alias, por el tipo de los
alumnos cuyo código de alumno no sea entre 1 y 4, siempre que la media
de las matrículas sea igual o superior a 145000. Ordenar por el total
mayor.
*/
/*
3.- De los alumnos que bien tengan en su descripción dos A en cualquier
parte o bien la longitud de la misma sea superior a 8, mostrar el nombre
junto con los miles de euros que pagan de matrícula, con el alias miles,
siempre dichos miles sean mayores o iguales a 145, ordenar por ellos de
mayor a menor.
*/
/*
4.- Transformar la anterior salida por pantalla a la siguiente,
*/
/*
5.- Transformar la salida del ejercicio 3 a la siguiente,
*/