1. Indica cuántos empleados ingresaron en el año 81 agrupando por fechas
y ordenando por la cuenta mayor

2. Cuenta los salarios iguales que tienen los empleados de Chicago.

3. Calcula para cada localidad la suma de salarios por un lado y la suma de
comisiones por otro, convirtiendo los nulos a cero, siempre que tengan
más de 3 empleados y la localidad no tenga dos C en cualquier parte.

4. Muestra de mayor a menor cuántos empleados subordinados tiene cada
jefe excluyendo al jefe que no tiene jefe.

5. Muestra el salario mayor, el salario menor y la media salarial sin
decimales de cada puesto de trabajo.

6. Queremos calcular y mostrar los mayores totales de salarios gastados en
la empresa por puesto de trabajo y nombre de departamento con las
condiciones de que exista jefe o la comisión no sea cero, excluyendo al
presidente y a los departamentos con una longitud de 5 caracteres.